language: cpp
sudo: required
dist: trusty
git:
  submodules: false
before_install:
  - git submodule update --init
os:
- linux
addons:
  apt:
    sources:
      - boost-latest
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - build-essential 
      - libboost-all-dev 
      - libcurl4-openssl-dev
      - gcc-7
script: 
- travis/buildenv.sh
- mkdir build
- cd build
- export CC=../../clang/bin/clang
- export CXX=../../clang/bin/clang++
- export LD_LIBRARY_PATH="../../clang/lib;${LD_LIBRARY_PATH}"
- ../../cmake/bin/cmake -DCMAKE_CXX_FLAGS="$CXX_FLAGS -Wall -pedantic  -stdlib=libc++ -DCLANG=true" ..
- make
- ./Tests/swarm-http-apiTests
